#!/bin/sh

sxhkd &

bspc monitor -d 1 2 3 4 5 6 7 8 9 10

bspc config border_width         1
bspc config window_gap          0

bspc config split_ratio          0.52
bspc config focus_follows_pointer  true
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config leaf_monocle true

killall -q polybar
while pgrep -u $UID -x polybar >/dev/null; do sleep 1; done
polybar default &
